# Dataset configuration untuk YOLOv8 Human Detection
# Path relatif dari root project

train: dataset/images/train
val: dataset/images/val

# Number of classes
nc: 1

# Class names
names: ['person']

